version: '3.8'

services:
  app-monitor:
    build: .
    container_name: ruperta-monitor
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
